### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by iraleigh** [seeds-of-creativity/home#10]
Someone needs to get Travic CI set up and watching the master branch and the development branch. Just an initial set up would be great, from there we can discuss what the build will actually incorporate.

Whoever takes on this task, I will probably have to grant ownership rights to the repo so that they can set it up. Please assign yourself and I will be happen to work with you and help any way that I can.

**Comment by echu10** [comment]
@jannton  would it be alright if I assign you to this? It looks like something I know you'll be awesome and great at!

**Comment by jannton** [comment]
i want to read up a bit on travis first before i jump on this, if i feel like i can do it, ill assign to myself, unless someone else wants it, then by all means. circling back next week

**Comment by jannton** [comment]
@echu10 your comment posted and i didn't even know until after i posted. whoops, but sure ok ill give it a shot!!

**Comment by iraleigh** [comment]
![screen shot 2017-07-31 at 6 40 50 pm](https://user-images.githubusercontent.com/9301649/28805567-e4303302-761f-11e7-9f68-3986fee29bf6.png)

I really like this workflow and would like to implement this

**Comment by iraleigh** [comment]
Closing this, as I am going to create more granular issues around this effort
