### ISSUE TITLE
Branching Strategy

### ISSUE THREAD

**Issue by jannton** [seeds-of-creativity/home#3]
Integration
Feature
Master 
(Suggestions)

**Comment by iraleigh** [comment]
I would like the master branch to always being a working version of the app. I am not sure if it should be a reflection of the current release, or if it should be a few steps ahead of the current release -- open to opinions here.

branching off of master would be a development branch that has not been through any sort of QA.

It would be great if we had a heroku instance running with both of these branches so we can do testing on these branches.

beyond that, I don't want release branches, as we should be continually releasing and not have to worry about different versions of the app floating around the branches.

two other branch types i am thinking of are feature branches off of the development branch and and hotfix (hopefully unnecessary) off of the master branch.

**Comment by iraleigh** [comment]
Totally open to ideas and opinions though, all that was just my initial idea

**Comment by iraleigh** [comment]
@jannton you have more dev ops experience, what do you think would be best?

**Comment by dianangyn** [comment]
As of 7/17/17: 
- **Feature**: Local/personal changes and builds. Create a peer review for any code changes before merging into development. 
- **Development**: Staging for working releases. (Travis CI upon merging onto Development.)
- **Master**: This is production. (Travis CI...)

**Comment by iraleigh** [comment]
I think we have settled on a branching strategy. Closing this issue.
