### ISSUE TITLE
Setup VOIP and Schedule Time to Chat

### ISSUE THREAD

**Issue by echu10** [seeds-of-creativity/home#6]
Are we using Skype as our main VOIP?

**Comment by iraleigh** [comment]
@echu10 what was the other tool that you mentioned?

**Comment by iraleigh** [comment]
@echu10 what was the other tool that you mentioned?

**Comment by echu10** [comment]
https://discord.gg/fnsjWD9

**Comment by echu10** [comment]
I'm usually free after 8PM most weekdays.

**Comment by iraleigh** [comment]
I like the idea of meeting at least once a week for now, so as to keep momentum, and build a solid foundation.

**Comment by jannton** [comment]
most days after 8PM is good for me too during the week
